#!/bin/sh

polybar &

bspc config window_gap           8
bspc config border_width         5
bspc config focused_border_color '#458588'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true

bspc monitor -d I II III IV # V VI VII VIII IX X

bspc rule -a feh state=floating
bspc rule -a Zathura state=tiled
